# Generated by Django 6.0.3 on 2026-03-28 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20)),
                ('experience_level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_remote', models.BooleanField(default=False)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to='users.admin')),
            ],
        ),
        migrations.CreateModel(
            name='JobCareer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_jobs', to='common.career')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_careers', to='jobs.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='careers',
            field=models.ManyToManyField(blank=True, related_name='jobs', through='jobs.JobCareer', to='common.career'),
        ),
        migrations.CreateModel(
            name='JobCertification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_jobs', to='common.certification')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_certifications', to='jobs.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='jobs', through='jobs.JobCertification', to='common.certification'),
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_jobs', to='common.skill')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobs', through='jobs.JobSkill', to='common.skill'),
        ),
        migrations.AddIndex(
            model_name='jobcareer',
            index=models.Index(fields=['job'], name='jobs_jobcar_job_id_e92ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcareer',
            index=models.Index(fields=['career'], name='jobs_jobcar_career__1f4499_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobcareer',
            unique_together={('job', 'career')},
        ),
        migrations.AddIndex(
            model_name='jobcertification',
            index=models.Index(fields=['job'], name='jobs_jobcer_job_id_67540f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcertification',
            index=models.Index(fields=['certification'], name='jobs_jobcer_certifi_deea26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobcertification',
            unique_together={('job', 'certification')},
        ),
        migrations.AddIndex(
            model_name='jobskill',
            index=models.Index(fields=['job'], name='jobs_jobski_job_id_ed41eb_idx'),
        ),
        migrations.AddIndex(
            model_name='jobskill',
            index=models.Index(fields=['skill'], name='jobs_jobski_skill_i_baab69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobskill',
            unique_together={('job', 'skill')},
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title'], name='jobs_job_title_0e1e41_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['slug'], name='jobs_job_slug_9562d1_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active'], name='jobs_job_is_acti_b6ae73_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['experience_level'], name='jobs_job_experie_09027f_idx'),
        ),
    ]
