# Generated by Django 6.0.3 on 2026-03-28 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('type', models.CharField(choices=[('skill', 'Skill'), ('certification', 'Certification'), ('career', 'Career')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='common_cate_name_d9bfc9_idx'), models.Index(fields=['slug'], name='common_cate_slug_ba850e_idx'), models.Index(fields=['type'], name='common_cate_type_a29898_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'type'), name='unique_category_per_type')],
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='careers/')),
                ('demand_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('average_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(limit_choices_to={'type': 'career'}, on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='common.category')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='common_care_name_fc66ff_idx'), models.Index(fields=['slug'], name='common_care_slug_61aacb_idx'), models.Index(fields=['demand_level'], name='common_care_demand__7ff4a7_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'category'), name='unique_career_per_category')],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True)),
                ('issuing_organization', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(limit_choices_to={'type': 'certification'}, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='common.category')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='common_cert_name_978de4_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'category'), name='unique_certification_per_category')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='skills/')),
                ('popularity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(limit_choices_to={'type': 'skill'}, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='common.category')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='common_skil_name_8eda67_idx'), models.Index(fields=['slug'], name='common_skil_slug_5828eb_idx'), models.Index(fields=['popularity'], name='common_skil_popular_0277db_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'category'), name='unique_skill_per_category')],
            },
        ),
    ]
