# Generated by Django 6.0.3 on 2026-03-28 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantCareer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_careers', to='users.applicant')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_applicants', to='common.career')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='careers',
            field=models.ManyToManyField(blank=True, related_name='applicants', through='users.ApplicantCareer', to='common.career'),
        ),
        migrations.CreateModel(
            name='ApplicantCertification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=255)),
                ('credential_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_certifications', to='users.applicant')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_applicants', to='common.certification')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='applicants', through='users.ApplicantCertification', to='common.certification'),
        ),
        migrations.CreateModel(
            name='ApplicantSkill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_skills', to='users.applicant')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_applicants', to='common.skill')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='applicants', through='users.ApplicantSkill', to='common.skill'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='companies.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company'], name='users_admin_company_8eed63_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='applicantcareer',
            index=models.Index(fields=['applicant'], name='users_appli_applica_523ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantcareer',
            index=models.Index(fields=['career'], name='users_appli_career__0c8363_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicantcareer',
            unique_together={('applicant', 'career')},
        ),
        migrations.AddIndex(
            model_name='applicantcertification',
            index=models.Index(fields=['applicant'], name='users_appli_applica_3a4428_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantcertification',
            index=models.Index(fields=['certification'], name='users_appli_certifi_f8671c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicantcertification',
            unique_together={('applicant', 'certification')},
        ),
        migrations.AddIndex(
            model_name='applicantskill',
            index=models.Index(fields=['applicant'], name='users_appli_applica_d27d14_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantskill',
            index=models.Index(fields=['skill'], name='users_appli_skill_i_eb1d91_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicantskill',
            unique_together={('applicant', 'skill')},
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['is_available'], name='users_appli_is_avai_efefff_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['location'], name='users_appli_locatio_b23ec9_idx'),
        ),
    ]
